// Packet-radio (TNC) service: a managed direwolf soundcard modem bridged to the radio's HFP
// audio + our PTT machinery, exposing a standard KISS TNC (TCP) and AGWPE port to the LAN.
//
//   RX  RxCapture ── one extra subscriber ── UDP :7355 ──→ direwolf ADEVICE udp:…
//   TX  direwolf ─→ snd-aloop playback ─→ arecord (capture end) ─→ radio HFP sink stdin
//   PTT direwolf ─→ hamlib NET rigctl :4532 (src/packet/rigctl.ts) ─→ radio key/unkey
//
// Why the asymmetry: direwolf consumes RX audio over UDP natively (gap-tolerant, zero lifecycle
// coupling), but it can only PLAY transmit audio into a real ALSA device — and it relies on that
// device's real-time drain to time its PTT release. The kernel loopback provides exactly those
// semantics; we read the mirror end and forward into the same sink path the browser mic uses.
//
// Everything here starts on enable() and tears down on disable() — zero footprint while off.
// The radio must be on an ANALOG channel with squelch open (SQL 0) for the modem to hear.

import { spawn, type ChildProcess } from 'node:child_process'
import { createSocket, type Socket } from 'node:dgram'
import { writeFile } from 'node:fs/promises'
import { basename, dirname } from 'node:path'
import { setTimeout as delay } from 'node:timers/promises'
import { RigctlServer, type RigctlPtt } from './rigctl'

/** The slice of the radio controller the service drives (adapter built in main.ts). */
export interface PacketRadio {
  key(): void
  unkey(): void
  pttPhase(): 'idle' | 'keying' | 'keyed' | 'unkeying' | 'fault'
  /** null = clear to transmit; otherwise the human-readable refusal (not connected / DMR channel). */
  txRefusal(): string | null
  /** The radio is actively RECEIVING right now (squelch bits / gate — radio truth). Direwolf's
   * own carrier detect lags this by the SCO audio path, and keying mid-RX is exactly when the
   * firmware silently drops the keydown (wire-diagnosed 2026-07-12). */
  rxBusy(): boolean
}

/** RX frame source (AudioBridge.capture) — subscribing starts the shared capture process. */
export interface FrameSource {
  subscribe(onFrame: (frame: Buffer) => void): Promise<() => void>
}

export type SinkFactory = () => { command: string; args: readonly string[] } | null

export interface PacketOptions {
  callsign: string
  kissPort: number
  agwPort: number
  udpPort: number
  rigctlPort: number
  /** direwolf's TX audio out — the loopback's playback end. */
  playbackDevice: string
  /** our mirror of it — the loopback's capture end. */
  captureDevice: string
  /** Rendered direwolf config path. KEEP SHORT — direwolf truncates paths around ~100 chars. */
  confPath: string
  /** Bonjour name for the KISS TNC advertisement (how RadioMail/PacketCommander list us). */
  mdnsName: string
  /** Wired RX capture device for the modem (e.g. the top-jack USB card, which carries the
   * SELECTED side). When set, direwolf gets a private 48 kHz capture — no CVSD, no BT AGC, no
   * other-side audio — instead of the shared 8 kHz Bluetooth tap. null = shared tap. */
  rxDevice: string | null
  /** PTT-confirmed → data start, ×10 ms (direwolf TXDELAY). Our chain is deeper than a wired
   * TNC's (BT ACK + SCO TX-path spin-up), so this runs longer than the classic 30. NOTE: KISS
   * clients can override it per-connection — those overrides are logged. */
  txDelay: number
  /** Hold after the last bit, ×10 ms (direwolf TXTAIL). */
  txTail: number
}

export const DEFAULT_PACKET_OPTIONS: PacketOptions = {
  callsign: 'N0CALL',
  kissPort: 8001,
  agwPort: 8000,
  udpPort: 7355,
  rigctlPort: 4532,
  playbackDevice: 'plughw:CARD=Loopback,DEV=0',
  captureDevice: 'plughw:CARD=Loopback,DEV=1',
  confPath: 'direwolf.conf',
  mdnsName: 'AnyTone D578 TNC',
  rxDevice: null,
  txDelay: 70,
  txTail: 5,
}

export interface PacketStatus {
  enabled: boolean
  /** direwolf process currently alive. */
  running: boolean
  /** direwolf holds the transmitter right now. */
  ptt: boolean
  decodes: number
  lastHeard: string | null
  /** direwolf's reported input level for the most recent decode (target ~50, clip ≥ ~90). */
  audioLevel: number | null
  kissPort: number
  agwPort: number
  error: string | null
}

/** The rendered direwolf config. 8 kHz native (the SCO rate — no resampling anywhere), 1200 baud
 * AFSK, PTT via our rigctl shim. KISS/AGW bind all interfaces (LAN clients are the point). */
export function renderConfig(o: PacketOptions): string {
  const arate = o.rxDevice ? 48000 : 8000
  return [
    `# generated by anytone-v2 — do not edit (rewritten on every packet-mode enable)`,
    `# RX source: ${o.rxDevice ?? 'shared Bluetooth tap (8 kHz CVSD)'}`,
    `ADEVICE udp:${o.udpPort} ${o.playbackDevice}`,
    `ARATE ${arate}`,
    `ACHANNELS 1`,
    `CHANNEL 0`,
    `MYCALL ${o.callsign}`,
    `MODEM 1200`,
    `PTT RIG 2 127.0.0.1:${o.rigctlPort}`,
    `TXDELAY ${o.txDelay}`,
    `TXTAIL ${o.txTail}`,
    `KISSPORT ${o.kissPort}`,
    `AGWPORT ${o.agwPort}`,
    ``,
  ].join('\n')
}

const UNKEY_SETTLE_TIMEOUT_MS = 2000
const PHASE_POLL_MS = 25
/** Hold the keydown until the radio reports RX-quiet, up to this long (then try anyway). */
const CHANNEL_CLEAR_TIMEOUT_MS = 2000
/** Fresh keydown attempts per T 1. ONE: the session's key() now retries the wire keydown itself
 * (KEY_MAX_ATTEMPTS bounded retransmits — the busy-gate recovery this loop used to provide), so
 * the packet layer just waits for the definitive outcome instead of second-guessing it. */
const KEY_ATTEMPTS = 1
/** Confirm window per attempt: the session's FULL keydown retry budget (3 × 1 s) + margin —
 * shorter windows misread a late-retransmit success as failure and release a good keydown. */
const KEY_ATTEMPT_ACK_MS = 3300
/** 8 kHz mono S16LE → 16 bytes of sink audio play out per millisecond. */
const SINK_BYTES_PER_MS = 16
/** Post-drain hold before the unkey: the radio is deaf to commands while finishing its TX tail —
 * an unkey sent into that window gets swallowed and costs an ARQ retransmit (wire-measured). */
const DRAIN_MARGIN_MS = 180
const RESTART_BACKOFF_MS = [1000, 2000, 5000, 10000] as const

export class PacketService implements RigctlPtt {
  private readonly rigctl: RigctlServer
  private readonly subscribers = new Set<(s: PacketStatus) => void>()

  private enabled = false
  private direwolf: ChildProcess | null = null
  private arecord: ChildProcess | null = null
  private mdns: ChildProcess | null = null
  private sinkProc: ChildProcess | null = null
  private udp: Socket | null = null
  private untap: (() => void) | null = null
  private restartCount = 0
  private restartTimer: ReturnType<typeof setTimeout> | null = null

  private pttHeld = false
  private keyedAt = 0
  private bytesWritten = 0

  private decodes = 0
  private lastHeard: string | null = null
  private audioLevel: number | null = null
  private rxCaptureProc: ChildProcess | null = null
  private lastError: string | null = null

  constructor(
    private readonly capture: FrameSource,
    private readonly sink: SinkFactory,
    private readonly radio: PacketRadio,
    private readonly opts: PacketOptions = DEFAULT_PACKET_OPTIONS,
    private readonly log: (m: string) => void = () => {},
    /** Injectable for tests (so enabling never runs real direwolf/arecord). */
    private readonly spawnFn: typeof spawn = spawn,
  ) {
    this.rigctl = new RigctlServer(this, log)
  }

  get keyed(): boolean {
    return this.pttHeld
  }

  get status(): PacketStatus {
    return {
      enabled: this.enabled,
      running: this.direwolf !== null,
      ptt: this.pttHeld,
      decodes: this.decodes,
      lastHeard: this.lastHeard,
      audioLevel: this.audioLevel,
      kissPort: this.opts.kissPort,
      agwPort: this.opts.agwPort,
      error: this.lastError,
    }
  }

  subscribe(cb: (s: PacketStatus) => void): () => void {
    this.subscribers.add(cb)
    return () => this.subscribers.delete(cb)
  }

  private emit(): void {
    const s = this.status
    for (const cb of this.subscribers) cb(s)
  }

  async enable(): Promise<PacketStatus> {
    if (this.enabled) return this.status
    this.lastError = null
    try {
      await writeFile(this.opts.confPath, renderConfig(this.opts))
      await this.rigctl.listen(this.opts.rigctlPort)
      this.udp = createSocket('udp4')
      if (this.opts.rxDevice === null) {
        // RX tap: every paced 10 ms capture frame → one datagram. Starts the shared capture if it
        // isn't running — which REQUIRES a connected radio, so enabling while disconnected fails here.
        this.untap = await this.capture.subscribe((frame) => {
          this.udp?.send(frame, this.opts.udpPort, '127.0.0.1')
        })
      }
      this.enabled = true
      this.startRxCapture() // no-op when the shared tap is in use
      this.startArecord()
      this.startDirewolf()
      this.startMdns()
    } catch (e) {
      this.lastError = (e as Error).message
      await this.teardown()
      this.emit()
      throw e
    }
    this.log(`packet: enabled (KISS :${this.opts.kissPort}, AGW :${this.opts.agwPort})`)
    this.emit()
    return this.status
  }

  async disable(): Promise<PacketStatus> {
    if (!this.enabled) return this.status
    this.enabled = false
    if (this.pttHeld) {
      // never leave the transmitter keyed behind a mode toggle — release WITHOUT the drain wait
      this.pttHeld = false
      this.sinkProc?.kill('SIGTERM')
      this.sinkProc = null
      try {
        this.radio.unkey()
      } catch {
        /* disconnected — nothing keyed through us */
      }
    }
    await this.teardown()
    this.log('packet: disabled')
    this.emit()
    return this.status
  }

  private async teardown(): Promise<void> {
    if (this.restartTimer) {
      clearTimeout(this.restartTimer)
      this.restartTimer = null
    }
    this.restartCount = 0
    this.direwolf?.kill('SIGTERM')
    this.direwolf = null
    this.arecord?.kill('SIGTERM')
    this.arecord = null
    this.rxCaptureProc?.kill('SIGTERM')
    this.rxCaptureProc = null
    this.mdns?.kill('SIGTERM')
    this.mdns = null
    this.untap?.()
    this.untap = null
    this.udp?.close()
    this.udp = null
    await this.rigctl.close()
  }

  // ── direwolf + loopback reader supervision ──────────────────────────────────

  private startDirewolf(): void {
    if (!this.enabled || this.direwolf) return
    // Relative -c from the conf's directory: direwolf truncates long absolute paths (~100 chars).
    const proc = this.spawnFn('direwolf', ['-t', '0', '-c', basename(this.opts.confPath)], {
      cwd: dirname(this.opts.confPath) || '.',
      stdio: ['ignore', 'pipe', 'pipe'],
    })
    this.direwolf = proc
    let out = ''
    proc.stdout?.on('data', (d: Buffer) => {
      out += d.toString('utf8')
      let nl: number
      while ((nl = out.indexOf('\n')) >= 0) {
        this.onDirewolfLine(out.slice(0, nl).trimEnd())
        out = out.slice(nl + 1)
      }
    })
    proc.stderr?.on('data', (d: Buffer) => this.log(`direwolf! ${d.toString().trim()}`))
    proc.on('error', (err) => {
      this.lastError = `direwolf spawn failed: ${err.message}`
      this.log(`packet: ${this.lastError}`)
    })
    proc.once('close', (code) => {
      if (this.direwolf === proc) this.direwolf = null
      this.log(`packet: direwolf exited (${code})`)
      this.emit()
      this.scheduleRestart()
    })
    this.log('packet: direwolf started')
  }

  /** Private wired RX capture for the modem (opts.rxDevice): 48 kHz mono straight off the jack,
   * chunked into ≤4 KB datagrams for direwolf's udp: input. Supervised like the other children. */
  private startRxCapture(): void {
    if (!this.enabled || this.rxCaptureProc || this.opts.rxDevice === null) return
    const proc = this.spawnFn(
      'arecord',
      ['-q', '-D', this.opts.rxDevice, '-f', 'S16_LE', '-r', '48000', '-c', '1', '-t', 'raw'],
      { stdio: ['ignore', 'pipe', 'pipe'] },
    )
    this.rxCaptureProc = proc
    proc.stdout?.on('data', (chunk: Buffer) => {
      for (let off = 0; off < chunk.length; off += 4096) {
        this.udp?.send(chunk.subarray(off, Math.min(off + 4096, chunk.length)), this.opts.udpPort, '127.0.0.1')
      }
    })
    proc.stderr?.on('data', (d: Buffer) => this.log(`rx-capture! ${d.toString().trim()}`))
    proc.on('error', (err) => this.log(`packet: rx capture spawn failed: ${err.message}`))
    proc.once('close', (code) => {
      if (this.rxCaptureProc === proc) this.rxCaptureProc = null
      if (this.enabled) this.log(`packet: rx capture exited (${code})`)
      this.scheduleRestart()
    })
    this.log(`packet: wired RX capture ${this.opts.rxDevice} (48 kHz)`)
  }

  private startArecord(): void {
    if (!this.enabled || this.arecord) return
    const proc = this.spawnFn(
      'arecord',
      ['-q', '-D', this.opts.captureDevice, '-f', 'S16_LE', '-r', '8000', '-c', '1', '-t', 'raw'],
      { stdio: ['ignore', 'pipe', 'pipe'] },
    )
    this.arecord = proc
    // TX return path: loopback audio only flows while direwolf is transmitting; forward to the
    // radio sink strictly while WE hold PTT (belt-and-braces — nothing should arrive otherwise).
    proc.stdout?.on('data', (chunk: Buffer) => {
      if (!this.pttHeld || !this.sinkProc?.stdin?.writable) return
      this.sinkProc.stdin.write(chunk)
      this.bytesWritten += chunk.length
    })
    proc.stderr?.on('data', (d: Buffer) => this.log(`arecord! ${d.toString().trim()}`))
    proc.on('error', (err) => this.log(`packet: arecord spawn failed: ${err.message}`))
    proc.once('close', (code) => {
      if (this.arecord === proc) this.arecord = null
      if (this.enabled) this.log(`packet: arecord exited (${code})`)
      this.scheduleRestart()
    })
  }

  /** Bonjour/DNS-SD advertisement of the KISS TNC (`_kiss-tnc._tcp`) — the direwolf 1.7
   * convention iOS packet apps (RadioMail, PacketCommander) browse for. The Debian direwolf is
   * built WITHOUT Avahi support, so we publish on its behalf via avahi-publish-service, scoped to
   * exactly the TNC's lifetime. Best-effort: a missing tool/daemon logs but never blocks enable. */
  private startMdns(): void {
    if (!this.enabled || this.mdns) return
    const proc = this.spawnFn(
      'avahi-publish-service',
      [this.opts.mdnsName, '_kiss-tnc._tcp', String(this.opts.kissPort)],
      { stdio: ['ignore', 'ignore', 'pipe'] },
    )
    this.mdns = proc
    proc.stderr?.on('data', (d: Buffer) => this.log(`mdns: ${d.toString().trim()}`))
    proc.on('error', (err) => this.log(`packet: mdns publish unavailable: ${err.message}`))
    proc.once('close', (code) => {
      if (this.mdns === proc) this.mdns = null
      if (this.enabled) this.log(`packet: mdns publisher exited (${code})`)
      this.scheduleRestart()
    })
    this.log(`packet: advertising "${this.opts.mdnsName}" (_kiss-tnc._tcp :${this.opts.kissPort})`)
  }

  private scheduleRestart(): void {
    if (!this.enabled || this.restartTimer) return
    const wait = RESTART_BACKOFF_MS[Math.min(this.restartCount, RESTART_BACKOFF_MS.length - 1)]!
    this.restartCount += 1
    this.restartTimer = setTimeout(() => {
      this.restartTimer = null
      if (!this.enabled) return
      this.startRxCapture()
      this.startArecord()
      this.startDirewolf()
      this.startMdns()
      this.emit()
      // a spell of stability resets the backoff ladder
      setTimeout(() => {
        if (this.direwolf) this.restartCount = 0
      }, 60_000).unref?.()
    }, wait)
    this.restartTimer.unref?.()
  }

  /** Decoded frames land on stdout as `[0.3] W1ABC-9>APRS,WIDE1-1:...` — count + remember them.
   * Also surface KISS parameter overrides: clients (RadioMail etc.) can push TXDELAY/TXTAIL over
   * KISS and silently replace the config values — that must be visible in the service log. */
  private onDirewolfLine(line: string): void {
    if (/KISS protocol set/i.test(line)) {
      this.log(`direwolf: ${line.trim()}`)
      return
    }
    const lvl = /audio level = (\d+)/.exec(line)
    if (lvl?.[1]) this.audioLevel = Number(lvl[1]) // emitted with the frame line that follows
    const m = /^\[\d[^\]]*\]\s+(.+)$/.exec(line)
    if (m?.[1] && m[1].includes('>')) {
      this.decodes += 1
      this.lastHeard = m[1].slice(0, 160)
      this.emit()
    }
  }

  // ── RigctlPtt: direwolf's PTT, routed through the radio's ACK-confirmed key path ──

  async key(): Promise<void> {
    if (!this.enabled) throw new Error('packet PTT refused: packet mode is off')
    const refusal = this.radio.txRefusal()
    if (refusal) throw new Error(`packet PTT refused: ${refusal}`)
    if (this.pttHeld) return
    if (this.radio.pttPhase() !== 'idle') throw new Error('packet PTT refused: transmitter busy')

    // Hold the keydown until the RADIO reports the channel quiet. Direwolf's DCD is derived from
    // the audio it hears — which trails radio truth by the SCO path — so it asks to key while the
    // radio is still mid-RX, and the firmware silently DROPS a 0x56 sent in that window.
    const clearBy = Date.now() + CHANNEL_CLEAR_TIMEOUT_MS
    while (this.enabled && this.radio.rxBusy() && Date.now() < clearBy) await delay(PHASE_POLL_MS)

    // ONE keydown, then wait out the definitive outcome: the session's key() owns the wire-level
    // retries now (bounded retransmits punch through the busy-gate), so the ack window here must
    // cover its FULL retry budget — a shorter wait would misread a late-retransmit success as
    // failure and release a good keydown. direwolf stays blocked on this T 1 throughout.
    for (let attempt = 1; attempt <= KEY_ATTEMPTS; attempt += 1) {
      const idleBy = Date.now() + 1500
      while (this.enabled && this.radio.pttPhase() !== 'idle' && Date.now() < idleBy) await delay(PHASE_POLL_MS)
      // disable() may have run while we waited — it saw pttHeld=false and had nothing to
      // release, so a keydown issued now would outlive the service. Abort before committing.
      if (!this.enabled) throw new Error('packet PTT refused: packet mode is off')
      if (this.radio.pttPhase() !== 'idle') break
      this.radio.key()
      const ackBy = Date.now() + KEY_ATTEMPT_ACK_MS
      while (this.radio.pttPhase() === 'keying' && Date.now() < ackBy) await delay(PHASE_POLL_MS)
      if (this.radio.pttPhase() === 'keyed') {
        if (!this.enabled) {
          // disabled while the radio was confirming — the keydown landed; release it here,
          // because disable() already ran its teardown with nothing to unkey.
          try {
            this.radio.unkey()
          } catch {
            /* disconnected — nothing keyed */
          }
          throw new Error('packet PTT refused: packet mode is off')
        }
        const cmd = this.sink()
        if (!cmd) {
          this.radio.unkey()
          throw new Error('packet PTT: no radio audio sink')
        }
        this.sinkProc = this.spawnFn(cmd.command, [...cmd.args], { stdio: ['pipe', 'ignore', 'pipe'] })
        this.sinkProc.on('error', (err) => this.log(`packet sink error: ${err.message}`))
        this.bytesWritten = 0
        this.keyedAt = Date.now()
        this.pttHeld = true
        this.log(`packet: PTT keyed (radio-confirmed${attempt > 1 ? `, attempt ${attempt}` : ''})`)
        this.emit()
        return
      }
      this.log(`packet: keydown attempt ${attempt}/${KEY_ATTEMPTS} not confirmed`)
    }
    try {
      this.radio.unkey()
    } catch {
      /* best effort */
    }
    throw new Error('packet PTT: radio did not confirm keydown')
  }

  async unkey(): Promise<void> {
    if (!this.pttHeld) return
    // direwolf believes its audio has finished playing (the loopback drained in real time);
    // whatever is still queued in OUR sink pipe needs bytes/rate ms to reach the air.
    const queuedMs = this.bytesWritten / SINK_BYTES_PER_MS - (Date.now() - this.keyedAt)
    const wait = Math.min(Math.max(queuedMs, 0) + DRAIN_MARGIN_MS, 2000)
    await delay(wait)
    if (!this.pttHeld) return // disable() force-released during the drain — already clean
    this.pttHeld = false
    this.sinkProc?.kill('SIGTERM')
    this.sinkProc = null
    try {
      this.radio.unkey()
    } catch {
      /* disconnected mid-TX — nothing to release */
    }
    const deadline = Date.now() + UNKEY_SETTLE_TIMEOUT_MS
    while (this.radio.pttPhase() !== 'idle' && this.radio.pttPhase() !== 'fault' && Date.now() < deadline) {
      await delay(PHASE_POLL_MS)
    }
    this.log('packet: PTT released')
    this.emit()
  }
}
